from flask import Flask
from flask_sqlalchemy import SQLAlchemy
import click

database = SQLAlchemy()

@click.command('seed')
def seed() -> None:
  """Seed the database."""
  from tracklift.models.equipment import Equipment
  from tracklift.models.muscle import Muscle
  from tracklift.models.exercise import Exercise

  Equipment(name = 'Barbell').add()
  Equipment(name = 'Bench Press Machine').add()
  Equipment(name = 'Cable Machine').add()
  Equipment(name = 'Crunch Machine').add()
  Equipment(name = 'Dumbbells').add()
  Equipment(name = 'Elliptical').add()
  Equipment(name = 'EZ Bar').add()
  Equipment(name = 'Kettlebell').add()
  Equipment(name = 'Lat Pulldown Machine').add()
  Equipment(name = 'Leg Curl Machine').add()
  Equipment(name = 'Leg Extension Machine').add()
  Equipment(name = 'Leg Press Machine').add()
  Equipment(name = 'Overhead Press Machine').add()
  Equipment(name = 'Pec Deck').add()
  Equipment(name = 'Seated Row Machine').add()
  Equipment(name = 'Smith Machine').add()
  Equipment(name = 'Stationary Bicycle').add()
  Equipment(name = 'Treadmill').add()

  Muscle(name = 'Abdomen').add()
  Muscle(name = 'Back').add()
  Muscle(name = 'Biceps').add()
  Muscle(name = 'Cardio').add()
  Muscle(name = 'Chest').add()
  Muscle(name = 'Legs').add()
  Muscle(name = 'Shoulders').add()
  Muscle(name = 'Triceps').add()

  Exercise(name = 'Back Squat (Barbell)', muscle_id = Muscle(name = 'Legs').get().id, equipment_id = Equipment(name = 'Barbell').get().id).add()
  Exercise(name = 'Back Squat (Smith Machine)', muscle_id = Muscle(name = 'Legs').get().id, equipment_id = Equipment(name = 'Smith Machine').get().id).add()
  Exercise(name = 'Bench Press (Decline, Barbell)', muscle_id = Muscle(name = 'Chest').get().id, equipment_id = Equipment(name = 'Barbell').get().id).add()
  Exercise(name = 'Bench Press (Decline, Dumbbell)', muscle_id = Muscle(name = 'Chest').get().id, equipment_id = Equipment(name = 'Dumbbells').get().id).add()
  Exercise(name = 'Bench Press (Decline, Smith Machine)', muscle_id = Muscle(name = 'Chest').get().id, equipment_id = Equipment(name = 'Smith Machine').get().id).add()
  Exercise(name = 'Bench Press (Flat, Barbell)', muscle_id = Muscle(name = 'Chest').get().id, equipment_id = Equipment(name = 'Barbell').get().id).add()
  Exercise(name = 'Bench Press (Flat, Bench Press Machine)', muscle_id = Muscle(name = 'Chest').get().id, equipment_id = Equipment(name = 'Bench Press Machine').get().id).add()
  Exercise(name = 'Bench Press (Flat, Dumbbell)', muscle_id = Muscle(name = 'Chest').get().id, equipment_id = Equipment(name = 'Dumbbells').get().id).add()
  Exercise(name = 'Bench Press (Flat, Smith Machine)', muscle_id = Muscle(name = 'Chest').get().id, equipment_id = Equipment(name = 'Smith Machine').get().id).add()
  Exercise(name = 'Bench Press (Incline, Barbell)', muscle_id = Muscle(name = 'Chest').get().id, equipment_id = Equipment(name = 'Barbell').get().id).add()
  Exercise(name = 'Bench Press (Incline, Dumbbell)', muscle_id = Muscle(name = 'Chest').get().id, equipment_id = Equipment(name = 'Dumbbells').get().id).add()
  Exercise(name = 'Bench Press (Incline, Smith Machine)', muscle_id = Muscle(name = 'Chest').get().id, equipment_id = Equipment(name = 'Smith Machine').get().id).add()
  Exercise(name = 'Bicep Curl (Cable)', muscle_id = Muscle(name = 'Biceps').get().id, equipment_id = Equipment(name = 'Cable Machine').get().id).add()
  Exercise(name = 'Bicep Curl (EZ Bar)', muscle_id = Muscle(name = 'Biceps').get().id, equipment_id = Equipment(name = 'EZ Bar').get().id).add()
  Exercise(name = 'Bicep Curl (Incline)', muscle_id = Muscle(name = 'Biceps').get().id, equipment_id = Equipment(name = 'Dumbbells').get().id).add()
  Exercise(name = 'Crunch (Cable)', muscle_id = Muscle(name = 'Abdomen').get().id, equipment_id = Equipment(name = 'Cable Machine').get().id).add()
  Exercise(name = 'Crunch (Machine)', muscle_id = Muscle(name = 'Abdomen').get().id, equipment_id = Equipment(name = 'Crunch Machine').get().id).add()
  Exercise(name = 'Face Pull', muscle_id = Muscle(name = 'Shoulders').get().id, equipment_id = Equipment(name = 'Cable Machine').get().id).add()
  Exercise(name = 'Goblet Squat', muscle_id = Muscle(name = 'Legs').get().id, equipment_id = Equipment(name = 'Dumbbells').get().id).add()
  Exercise(name = 'Lat Pulldown (Standard)', muscle_id = Muscle(name = 'Back').get().id, equipment_id = Equipment(name = 'Lat Pulldown Machine').get().id).add()
  Exercise(name = 'Lat Pulldown (Straight Arm)', muscle_id = Muscle(name = 'Back').get().id, equipment_id = Equipment(name = 'Lat Pulldown Machine').get().id).add()
  Exercise(name = 'Lat Pulldown (Underhand)', muscle_id = Muscle(name = 'Back').get().id, equipment_id = Equipment(name = 'Lat Pulldown Machine').get().id).add()
  Exercise(name = 'Lat Pulldown (V-Bar)', muscle_id = Muscle(name = 'Back').get().id, equipment_id = Equipment(name = 'Lat Pulldown Machine').get().id).add()
  Exercise(name = 'Lateral Raise (Cable)', muscle_id = Muscle(name = 'Shoulders').get().id, equipment_id = Equipment(name = 'Cable Machine').get().id).add()
  Exercise(name = 'Lateral Raise (Dumbbell)', muscle_id = Muscle(name = 'Shoulders').get().id, equipment_id = Equipment(name = 'Dumbbells').get().id).add()
  Exercise(name = 'Leg Extension', muscle_id = Muscle(name = 'Legs').get().id, equipment_id = Equipment(name = 'Leg Extension Machine').get().id).add()
  Exercise(name = 'Leg Press', muscle_id = Muscle(name = 'Legs').get().id, equipment_id = Equipment(name = 'Leg Press Machine').get().id).add()
  Exercise(name = 'Overhead Press (Barbell)', muscle_id = Muscle(name = 'Shoulders').get().id, equipment_id = Equipment(name = 'Barbell').get().id).add()
  Exercise(name = 'Overhead Press (Dumbbell)', muscle_id = Muscle(name = 'Shoulders').get().id, equipment_id = Equipment(name = 'Dumbbells').get().id).add()
  Exercise(name = 'Overhead Press (Overhead Press Machine)', muscle_id = Muscle(name = 'Shoulders').get().id, equipment_id = Equipment(name = 'Overhead Press Machine').get().id).add()
  Exercise(name = 'Overhead Press (Smith Machine)', muscle_id = Muscle(name = 'Shoulders').get().id, equipment_id = Equipment(name = 'Smith Machine').get().id).add()
  Exercise(name = 'Overhead Tricep Extension (Cable)', muscle_id = Muscle(name = 'Triceps').get().id, equipment_id = Equipment(name = 'Cable Machine').get().id).add()
  Exercise(name = 'Overhead Tricep Extension (Dumbbell)', muscle_id = Muscle(name = 'Triceps').get().id, equipment_id = Equipment(name = 'Dumbbells').get().id).add()
  Exercise(name = 'Pec Deck', muscle_id = Muscle(name = 'Chest').get().id, equipment_id = Equipment(name = 'Pec Deck').get().id).add()
  Exercise(name = 'Preacher Curl (EZ Bar)', muscle_id = Muscle(name = 'Biceps').get().id, equipment_id = Equipment(name = 'EZ Bar').get().id).add()
  Exercise(name = 'Romanian Deadlift (Barbell)', muscle_id = Muscle(name = 'Legs').get().id, equipment_id = Equipment(name = 'Barbell').get().id).add()
  Exercise(name = 'Romanian Deadlift (Dumbbell)', muscle_id = Muscle(name = 'Legs').get().id, equipment_id = Equipment(name = 'Dumbbells').get().id).add()
  Exercise(name = 'Row (Dumbbell)', muscle_id = Muscle(name = 'Back').get().id, equipment_id = Equipment(name = 'Dumbbells').get().id).add()
  Exercise(name = 'Run (Treadmill)', muscle_id = Muscle(name = 'Cardio').get().id, equipment_id = Equipment(name = 'Treadmill').get().id).add()
  Exercise(name = 'Seated Row', muscle_id = Muscle(name = 'Back').get().id, equipment_id = Equipment(name = 'Seated Row Machine').get().id).add()
  Exercise(name = 'Shrug (Barbell)', muscle_id = Muscle(name = 'Shoulders').get().id, equipment_id = Equipment(name = 'Barbell').get().id).add()
  Exercise(name = 'Shrug (Dumbbell)', muscle_id = Muscle(name = 'Shoulders').get().id, equipment_id = Equipment(name = 'Dumbbells').get().id).add()
  Exercise(name = 'Skull Crusher (EZ Bar)', muscle_id = Muscle(name = 'Triceps').get().id, equipment_id = Equipment(name = 'EZ Bar').get().id).add()
  Exercise(name = 'Tricep Pushdown (Rope)', muscle_id = Muscle(name = 'Triceps').get().id, equipment_id = Equipment(name = 'Cable Machine').get().id).add()
  Exercise(name = 'Tricep Pushdown (Straight Bar)', muscle_id = Muscle(name = 'Triceps').get().id, equipment_id = Equipment(name = 'Cable Machine').get().id).add()
  Exercise(name = 'Walk (Treadmill)', muscle_id = Muscle(name = 'Cardio').get().id, equipment_id = Equipment(name = 'Treadmill').get().id).add()

  click.echo('Added seed data to the database.')

def register_commands(app: Flask) -> None:
  """Register CLI commands."""
  app.cli.add_command(seed)
