"""empty message

Revision ID: 4c77b81b7733
Revises:
Create Date: 2025-02-13 00:28:14.419072

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '4c77b81b7733'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('date_added', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('muscles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('date_added', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('workouts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('date_added', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('exercises',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('muscle_id', sa.UUID(), nullable=True),
    sa.Column('equipment_id', sa.UUID(), nullable=False),
    sa.Column('date_added', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['muscle_id'], ['muscles.id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('workout_exercises',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workout_id', sa.UUID(), nullable=False),
    sa.Column('exercise_id', sa.UUID(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('date_added', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workout_exercise_id', sa.UUID(), nullable=False),
    sa.Column('repetitions', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('date_added', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['workout_exercise_id'], ['workout_exercises.id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute("INSERT INTO equipment (id, name, date_added) VALUES (gen_random_uuid(), 'Barbell', TIMEZONE('utc', NOW()));")
    op.execute("INSERT INTO equipment (id, name, date_added) VALUES (gen_random_uuid(), 'Bench Press Machine', TIMEZONE('utc', NOW()));")
    op.execute("INSERT INTO equipment (id, name, date_added) VALUES (gen_random_uuid(), 'Cable Machine', TIMEZONE('utc', NOW()));")
    op.execute("INSERT INTO equipment (id, name, date_added) VALUES (gen_random_uuid(), 'Crunch Machine', TIMEZONE('utc', NOW()));")
    op.execute("INSERT INTO equipment (id, name, date_added) VALUES (gen_random_uuid(), 'Dumbbells', TIMEZONE('utc', NOW()));")
    op.execute("INSERT INTO equipment (id, name, date_added) VALUES (gen_random_uuid(), 'Elliptical', TIMEZONE('utc', NOW()));")
    op.execute("INSERT INTO equipment (id, name, date_added) VALUES (gen_random_uuid(), 'EZ Bar', TIMEZONE('utc', NOW()));")
    op.execute("INSERT INTO equipment (id, name, date_added) VALUES (gen_random_uuid(), 'Kettlebell', TIMEZONE('utc', NOW()));")
    op.execute("INSERT INTO equipment (id, name, date_added) VALUES (gen_random_uuid(), 'Lat Pulldown Machine', TIMEZONE('utc', NOW()));")
    op.execute("INSERT INTO equipment (id, name, date_added) VALUES (gen_random_uuid(), 'Leg Curl Machine', TIMEZONE('utc', NOW()));")
    op.execute("INSERT INTO equipment (id, name, date_added) VALUES (gen_random_uuid(), 'Leg Extension Machine', TIMEZONE('utc', NOW()));")
    op.execute("INSERT INTO equipment (id, name, date_added) VALUES (gen_random_uuid(), 'Leg Press Machine', TIMEZONE('utc', NOW()));")
    op.execute("INSERT INTO equipment (id, name, date_added) VALUES (gen_random_uuid(), 'Overhead Press Machine', TIMEZONE('utc', NOW()));")
    op.execute("INSERT INTO equipment (id, name, date_added) VALUES (gen_random_uuid(), 'Pec Deck', TIMEZONE('utc', NOW()));")
    op.execute("INSERT INTO equipment (id, name, date_added) VALUES (gen_random_uuid(), 'Seated Row Machine', TIMEZONE('utc', NOW()));")
    op.execute("INSERT INTO equipment (id, name, date_added) VALUES (gen_random_uuid(), 'Smith Machine', TIMEZONE('utc', NOW()));")
    op.execute("INSERT INTO equipment (id, name, date_added) VALUES (gen_random_uuid(), 'Stationary Bicycle', TIMEZONE('utc', NOW()));")
    op.execute("INSERT INTO equipment (id, name, date_added) VALUES (gen_random_uuid(), 'Treadmill', TIMEZONE('utc', NOW()));")

    op.execute("INSERT INTO muscles (id, name, date_added) VALUES (gen_random_uuid(), 'Abdomen', TIMEZONE('utc', NOW()));")
    op.execute("INSERT INTO muscles (id, name, date_added) VALUES (gen_random_uuid(), 'Back', TIMEZONE('utc', NOW()));")
    op.execute("INSERT INTO muscles (id, name, date_added) VALUES (gen_random_uuid(), 'Biceps', TIMEZONE('utc', NOW()));")
    op.execute("INSERT INTO muscles (id, name, date_added) VALUES (gen_random_uuid(), 'Cardio', TIMEZONE('utc', NOW()));")
    op.execute("INSERT INTO muscles (id, name, date_added) VALUES (gen_random_uuid(), 'Chest', TIMEZONE('utc', NOW()));")
    op.execute("INSERT INTO muscles (id, name, date_added) VALUES (gen_random_uuid(), 'Legs', TIMEZONE('utc', NOW()));")
    op.execute("INSERT INTO muscles (id, name, date_added) VALUES (gen_random_uuid(), 'Shoulders', TIMEZONE('utc', NOW()));")
    op.execute("INSERT INTO muscles (id, name, date_added) VALUES (gen_random_uuid(), 'Triceps', TIMEZONE('utc', NOW()));")

    op.execute("INSERT INTO exercises (id, date_added, name, muscle_id, equipment_id) SELECT gen_random_uuid(), TIMEZONE('utc', NOW()), 'Back Squat (Barbell)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Legs' AND e.name = 'Barbell';")
    op.execute("INSERT INTO exercises (id, date_added, name, muscle_id, equipment_id) SELECT gen_random_uuid(), TIMEZONE('utc', NOW()), 'Back Squat (Smith Machine)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Legs' AND e.name = 'Smith Machine';")
    op.execute("INSERT INTO exercises (id, date_added, name, muscle_id, equipment_id) SELECT gen_random_uuid(), TIMEZONE('utc', NOW()), 'Bench Press (Decline, Barbell)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Chest' AND e.name = 'Barbell';")
    op.execute("INSERT INTO exercises (id, date_added, name, muscle_id, equipment_id) SELECT gen_random_uuid(), TIMEZONE('utc', NOW()), 'Bench Press (Decline, Dumbbell)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Chest' AND e.name = 'Dumbbells';")
    op.execute("INSERT INTO exercises (id, date_added, name, muscle_id, equipment_id) SELECT gen_random_uuid(), TIMEZONE('utc', NOW()), 'Bench Press (Decline, Smith Machine)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Chest' AND e.name = 'Smith Machine';")
    op.execute("INSERT INTO exercises (id, date_added, name, muscle_id, equipment_id) SELECT gen_random_uuid(), TIMEZONE('utc', NOW()), 'Bench Press (Flat, Barbell)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Chest' AND e.name = 'Barbell';")
    op.execute("INSERT INTO exercises (id, date_added, name, muscle_id, equipment_id) SELECT gen_random_uuid(), TIMEZONE('utc', NOW()), 'Bench Press (Flat, Bench Press Machine)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Chest' AND e.name = 'Bench Press Machine';")
    op.execute("INSERT INTO exercises (id, date_added, name, muscle_id, equipment_id) SELECT gen_random_uuid(), TIMEZONE('utc', NOW()), 'Bench Press (Flat, Dumbbell)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Chest' AND e.name = 'Dumbbells';")
    op.execute("INSERT INTO exercises (id, date_added, name, muscle_id, equipment_id) SELECT gen_random_uuid(), TIMEZONE('utc', NOW()), 'Bench Press (Flat, Smith Machine)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Chest' AND e.name = 'Smith Machine';")
    op.execute("INSERT INTO exercises (id, date_added, name, muscle_id, equipment_id) SELECT gen_random_uuid(), TIMEZONE('utc', NOW()), 'Bench Press (Incline, Barbell)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Chest' AND e.name = 'Barbell';")
    op.execute("INSERT INTO exercises (id, date_added, name, muscle_id, equipment_id) SELECT gen_random_uuid(), TIMEZONE('utc', NOW()), 'Bench Press (Incline, Dumbbell)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Chest' AND e.name = 'Dumbbells';")
    op.execute("INSERT INTO exercises (id, date_added, name, muscle_id, equipment_id) SELECT gen_random_uuid(), TIMEZONE('utc', NOW()), 'Bench Press (Incline, Smith Machine)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Chest' AND e.name = 'Smith Machine';")
    op.execute("INSERT INTO exercises (id, date_added, name, muscle_id, equipment_id) SELECT gen_random_uuid(), TIMEZONE('utc', NOW()), 'Bicep Curl (Cable)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Biceps' AND e.name = 'Cable Machine';")
    op.execute("INSERT INTO exercises (id, date_added, name, muscle_id, equipment_id) SELECT gen_random_uuid(), TIMEZONE('utc', NOW()), 'Bicep Curl (EZ Bar)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Biceps' AND e.name = 'EZ Bar';")
    op.execute("INSERT INTO exercises (id, date_added, name, muscle_id, equipment_id) SELECT gen_random_uuid(), TIMEZONE('utc', NOW()), 'Bicep Curl (Incline)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Biceps' AND e.name = 'Dumbbells';")
    op.execute("INSERT INTO exercises (id, date_added, name, muscle_id, equipment_id) SELECT gen_random_uuid(), TIMEZONE('utc', NOW()), 'Crunch (Cable)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Abdomen' AND e.name = 'Cable Machine';")
    op.execute("INSERT INTO exercises (id, date_added, name, muscle_id, equipment_id) SELECT gen_random_uuid(), TIMEZONE('utc', NOW()), 'Crunch (Machine)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Abdomen' AND e.name = 'Crunch Machine';")
    op.execute("INSERT INTO exercises (id, date_added, name, muscle_id, equipment_id) SELECT gen_random_uuid(), TIMEZONE('utc', NOW()), 'Face Pull', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Shoulders' AND e.name = 'Cable Machine';")
    op.execute("INSERT INTO exercises (id, date_added, name, muscle_id, equipment_id) SELECT gen_random_uuid(), TIMEZONE('utc', NOW()), 'Goblet Squat', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Legs' AND e.name = 'Dumbbells';")
    op.execute("INSERT INTO exercises (id, date_added, name, muscle_id, equipment_id) SELECT gen_random_uuid(), TIMEZONE('utc', NOW()), 'Lat Pulldown (Standard)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Back' AND e.name = 'Lat Pulldown Machine';")
    op.execute("INSERT INTO exercises (id, date_added, name, muscle_id, equipment_id) SELECT gen_random_uuid(), TIMEZONE('utc', NOW()), 'Lat Pulldown (Straight Arm)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Back' AND e.name = 'Lat Pulldown Machine';")
    op.execute("INSERT INTO exercises (id, date_added, name, muscle_id, equipment_id) SELECT gen_random_uuid(), TIMEZONE('utc', NOW()), 'Lat Pulldown (Underhand)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Back' AND e.name = 'Lat Pulldown Machine';")
    op.execute("INSERT INTO exercises (id, date_added, name, muscle_id, equipment_id) SELECT gen_random_uuid(), TIMEZONE('utc', NOW()), 'Lat Pulldown (V-Bar)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Back' AND e.name = 'Lat Pulldown Machine';")
    op.execute("INSERT INTO exercises (id, date_added, name, muscle_id, equipment_id) SELECT gen_random_uuid(), TIMEZONE('utc', NOW()), 'Lateral Raise (Cable)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Shoulders' AND e.name = 'Cable Machine';")
    op.execute("INSERT INTO exercises (id, date_added, name, muscle_id, equipment_id) SELECT gen_random_uuid(), TIMEZONE('utc', NOW()), 'Lateral Raise (Dumbbell)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Shoulders' AND e.name = 'Dumbbells';")
    op.execute("INSERT INTO exercises (id, date_added, name, muscle_id, equipment_id) SELECT gen_random_uuid(), TIMEZONE('utc', NOW()), 'Leg Extension', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Legs' AND e.name = 'Leg Extension Machine';")
    op.execute("INSERT INTO exercises (id, date_added, name, muscle_id, equipment_id) SELECT gen_random_uuid(), TIMEZONE('utc', NOW()), 'Leg Press', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Legs' AND e.name = 'Leg Press Machine';")
    op.execute("INSERT INTO exercises (id, date_added, name, muscle_id, equipment_id) SELECT gen_random_uuid(), TIMEZONE('utc', NOW()), 'Overhead Press (Barbell)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Shoulders' AND e.name = 'Barbell';")
    op.execute("INSERT INTO exercises (id, date_added, name, muscle_id, equipment_id) SELECT gen_random_uuid(), TIMEZONE('utc', NOW()), 'Overhead Press (Dumbbell)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Shoulders' AND e.name = 'Dumbbells';")
    op.execute("INSERT INTO exercises (id, date_added, name, muscle_id, equipment_id) SELECT gen_random_uuid(), TIMEZONE('utc', NOW()), 'Overhead Press (Overhead Press Machine)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Shoulders' AND e.name = 'Overhead Press Machine';")
    op.execute("INSERT INTO exercises (id, date_added, name, muscle_id, equipment_id) SELECT gen_random_uuid(), TIMEZONE('utc', NOW()), 'Overhead Press (Smith Machine)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Shoulders' AND e.name = 'Smith Machine';")
    op.execute("INSERT INTO exercises (id, date_added, name, muscle_id, equipment_id) SELECT gen_random_uuid(), TIMEZONE('utc', NOW()), 'Overhead Tricep Extension (Cable)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Triceps' AND e.name = 'Cable Machine';")
    op.execute("INSERT INTO exercises (id, date_added, name, muscle_id, equipment_id) SELECT gen_random_uuid(), TIMEZONE('utc', NOW()), 'Overhead Tricep Extension (Dumbbell)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Triceps' AND e.name = 'Dumbbells';")
    op.execute("INSERT INTO exercises (id, date_added, name, muscle_id, equipment_id) SELECT gen_random_uuid(), TIMEZONE('utc', NOW()), 'Pec Deck', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Chest' AND e.name = 'Pec Deck';")
    op.execute("INSERT INTO exercises (id, date_added, name, muscle_id, equipment_id) SELECT gen_random_uuid(), TIMEZONE('utc', NOW()), 'Preacher Curl (EZ Bar)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Biceps' AND e.name = 'EZ Bar';")
    op.execute("INSERT INTO exercises (id, date_added, name, muscle_id, equipment_id) SELECT gen_random_uuid(), TIMEZONE('utc', NOW()), 'Romanian Deadlift (Barbell)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Legs' AND e.name = 'Barbell';")
    op.execute("INSERT INTO exercises (id, date_added, name, muscle_id, equipment_id) SELECT gen_random_uuid(), TIMEZONE('utc', NOW()), 'Romanian Deadlift (Dumbbell)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Legs' AND e.name = 'Dumbbells';")
    op.execute("INSERT INTO exercises (id, date_added, name, muscle_id, equipment_id) SELECT gen_random_uuid(), TIMEZONE('utc', NOW()), 'Row (Dumbbell)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Back' AND e.name = 'Dumbbells';")
    op.execute("INSERT INTO exercises (id, date_added, name, muscle_id, equipment_id) SELECT gen_random_uuid(), TIMEZONE('utc', NOW()), 'Run (Treadmill)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Cardio' AND e.name = 'Treadmill';")
    op.execute("INSERT INTO exercises (id, date_added, name, muscle_id, equipment_id) SELECT gen_random_uuid(), TIMEZONE('utc', NOW()), 'Seated Row', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Back' AND e.name = 'Seated Row Machine';")
    op.execute("INSERT INTO exercises (id, date_added, name, muscle_id, equipment_id) SELECT gen_random_uuid(), TIMEZONE('utc', NOW()), 'Shrug (Barbell)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Shoulders' AND e.name = 'Barbell';")
    op.execute("INSERT INTO exercises (id, date_added, name, muscle_id, equipment_id) SELECT gen_random_uuid(), TIMEZONE('utc', NOW()), 'Shrug (Dumbbell)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Shoulders' AND e.name = 'Dumbbells';")
    op.execute("INSERT INTO exercises (id, date_added, name, muscle_id, equipment_id) SELECT gen_random_uuid(), TIMEZONE('utc', NOW()), 'Skull Crusher (EZ Bar)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Triceps' AND e.name = 'EZ Bar';")
    op.execute("INSERT INTO exercises (id, date_added, name, muscle_id, equipment_id) SELECT gen_random_uuid(), TIMEZONE('utc', NOW()), 'Tricep Pushdown (Rope)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Triceps' AND e.name = 'Cable Machine';")
    op.execute("INSERT INTO exercises (id, date_added, name, muscle_id, equipment_id) SELECT gen_random_uuid(), TIMEZONE('utc', NOW()), 'Tricep Pushdown (Straight Bar)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Triceps' AND e.name = 'Cable Machine';")
    op.execute("INSERT INTO exercises (id, date_added, name, muscle_id, equipment_id) SELECT gen_random_uuid(), TIMEZONE('utc', NOW()), 'Walk (Treadmill)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Cardio' AND e.name = 'Treadmill';")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sets')
    op.drop_table('workout_exercises')
    op.drop_table('exercises')
    op.drop_table('workouts')
    op.drop_table('muscles')
    op.drop_table('equipment')
    # ### end Alembic commands ###
