"""seed_data

Revision ID: 4ff0600e5ebd
Revises: cecdbaf9ab48
Create Date: 2025-02-14 22:00:37.914438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ff0600e5ebd'
down_revision = 'cecdbaf9ab48'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("INSERT INTO equipment (name) VALUES ('Barbell');")
    op.execute("INSERT INTO equipment (name) VALUES ('Bench Press Machine');")
    op.execute("INSERT INTO equipment (name) VALUES ('Cable Machine');")
    op.execute("INSERT INTO equipment (name) VALUES ('Crunch Machine');")
    op.execute("INSERT INTO equipment (name) VALUES ('Dumbbells');")
    op.execute("INSERT INTO equipment (name) VALUES ('Elliptical');")
    op.execute("INSERT INTO equipment (name) VALUES ('EZ Bar');")
    op.execute("INSERT INTO equipment (name) VALUES ('Kettlebell');")
    op.execute("INSERT INTO equipment (name) VALUES ('Lat Pulldown Machine');")
    op.execute("INSERT INTO equipment (name) VALUES ('Leg Curl Machine');")
    op.execute("INSERT INTO equipment (name) VALUES ('Leg Extension Machine');")
    op.execute("INSERT INTO equipment (name) VALUES ('Leg Press Machine');")
    op.execute("INSERT INTO equipment (name) VALUES ('Overhead Press Machine');")
    op.execute("INSERT INTO equipment (name) VALUES ('Pec Deck');")
    op.execute("INSERT INTO equipment (name) VALUES ('Seated Row Machine');")
    op.execute("INSERT INTO equipment (name) VALUES ('Smith Machine');")
    op.execute("INSERT INTO equipment (name) VALUES ('Stationary Bicycle');")
    op.execute("INSERT INTO equipment (name) VALUES ('Treadmill');")
    op.execute("INSERT INTO muscles (name) VALUES ('Abdomen');")
    op.execute("INSERT INTO muscles (name) VALUES ('Back');")
    op.execute("INSERT INTO muscles (name) VALUES ('Biceps');")
    op.execute("INSERT INTO muscles (name) VALUES ('Cardio');")
    op.execute("INSERT INTO muscles (name) VALUES ('Chest');")
    op.execute("INSERT INTO muscles (name) VALUES ('Legs');")
    op.execute("INSERT INTO muscles (name) VALUES ('Shoulders');")
    op.execute("INSERT INTO muscles (name) VALUES ('Triceps');")
    op.execute("INSERT INTO exercises (name, muscle_id, equipment_id) SELECT 'Back Squat (Barbell)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Legs' AND e.name = 'Barbell';")
    op.execute("INSERT INTO exercises (name, muscle_id, equipment_id) SELECT 'Back Squat (Smith Machine)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Legs' AND e.name = 'Smith Machine';")
    op.execute("INSERT INTO exercises (name, muscle_id, equipment_id) SELECT 'Bench Press (Decline, Barbell)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Chest' AND e.name = 'Barbell';")
    op.execute("INSERT INTO exercises (name, muscle_id, equipment_id) SELECT 'Bench Press (Decline, Dumbbell)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Chest' AND e.name = 'Dumbbells';")
    op.execute("INSERT INTO exercises (name, muscle_id, equipment_id) SELECT 'Bench Press (Decline, Smith Machine)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Chest' AND e.name = 'Smith Machine';")
    op.execute("INSERT INTO exercises (name, muscle_id, equipment_id) SELECT 'Bench Press (Flat, Barbell)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Chest' AND e.name = 'Barbell';")
    op.execute("INSERT INTO exercises (name, muscle_id, equipment_id) SELECT 'Bench Press (Flat, Bench Press Machine)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Chest' AND e.name = 'Bench Press Machine';")
    op.execute("INSERT INTO exercises (name, muscle_id, equipment_id) SELECT 'Bench Press (Flat, Dumbbell)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Chest' AND e.name = 'Dumbbells';")
    op.execute("INSERT INTO exercises (name, muscle_id, equipment_id) SELECT 'Bench Press (Flat, Smith Machine)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Chest' AND e.name = 'Smith Machine';")
    op.execute("INSERT INTO exercises (name, muscle_id, equipment_id) SELECT 'Bench Press (Incline, Barbell)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Chest' AND e.name = 'Barbell';")
    op.execute("INSERT INTO exercises (name, muscle_id, equipment_id) SELECT 'Bench Press (Incline, Dumbbell)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Chest' AND e.name = 'Dumbbells';")
    op.execute("INSERT INTO exercises (name, muscle_id, equipment_id) SELECT 'Bench Press (Incline, Smith Machine)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Chest' AND e.name = 'Smith Machine';")
    op.execute("INSERT INTO exercises (name, muscle_id, equipment_id) SELECT 'Bicep Curl (Cable)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Biceps' AND e.name = 'Cable Machine';")
    op.execute("INSERT INTO exercises (name, muscle_id, equipment_id) SELECT 'Bicep Curl (EZ Bar)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Biceps' AND e.name = 'EZ Bar';")
    op.execute("INSERT INTO exercises (name, muscle_id, equipment_id) SELECT 'Bicep Curl (Incline)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Biceps' AND e.name = 'Dumbbells';")
    op.execute("INSERT INTO exercises (name, muscle_id, equipment_id) SELECT 'Crunch (Cable)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Abdomen' AND e.name = 'Cable Machine';")
    op.execute("INSERT INTO exercises (name, muscle_id, equipment_id) SELECT 'Crunch (Machine)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Abdomen' AND e.name = 'Crunch Machine';")
    op.execute("INSERT INTO exercises (name, muscle_id, equipment_id) SELECT 'Face Pull', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Shoulders' AND e.name = 'Cable Machine';")
    op.execute("INSERT INTO exercises (name, muscle_id, equipment_id) SELECT 'Goblet Squat', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Legs' AND e.name = 'Dumbbells';")
    op.execute("INSERT INTO exercises (name, muscle_id, equipment_id) SELECT 'Lat Pulldown (Standard)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Back' AND e.name = 'Lat Pulldown Machine';")
    op.execute("INSERT INTO exercises (name, muscle_id, equipment_id) SELECT 'Lat Pulldown (Straight Arm)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Back' AND e.name = 'Lat Pulldown Machine';")
    op.execute("INSERT INTO exercises (name, muscle_id, equipment_id) SELECT 'Lat Pulldown (Underhand)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Back' AND e.name = 'Lat Pulldown Machine';")
    op.execute("INSERT INTO exercises (name, muscle_id, equipment_id) SELECT 'Lat Pulldown (V-Bar)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Back' AND e.name = 'Lat Pulldown Machine';")
    op.execute("INSERT INTO exercises (name, muscle_id, equipment_id) SELECT 'Lateral Raise (Cable)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Shoulders' AND e.name = 'Cable Machine';")
    op.execute("INSERT INTO exercises (name, muscle_id, equipment_id) SELECT 'Lateral Raise (Dumbbell)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Shoulders' AND e.name = 'Dumbbells';")
    op.execute("INSERT INTO exercises (name, muscle_id, equipment_id) SELECT 'Leg Extension', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Legs' AND e.name = 'Leg Extension Machine';")
    op.execute("INSERT INTO exercises (name, muscle_id, equipment_id) SELECT 'Leg Press', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Legs' AND e.name = 'Leg Press Machine';")
    op.execute("INSERT INTO exercises (name, muscle_id, equipment_id) SELECT 'Overhead Press (Barbell)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Shoulders' AND e.name = 'Barbell';")
    op.execute("INSERT INTO exercises (name, muscle_id, equipment_id) SELECT 'Overhead Press (Dumbbell)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Shoulders' AND e.name = 'Dumbbells';")
    op.execute("INSERT INTO exercises (name, muscle_id, equipment_id) SELECT 'Overhead Press (Overhead Press Machine)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Shoulders' AND e.name = 'Overhead Press Machine';")
    op.execute("INSERT INTO exercises (name, muscle_id, equipment_id) SELECT 'Overhead Press (Smith Machine)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Shoulders' AND e.name = 'Smith Machine';")
    op.execute("INSERT INTO exercises (name, muscle_id, equipment_id) SELECT 'Overhead Tricep Extension (Cable)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Triceps' AND e.name = 'Cable Machine';")
    op.execute("INSERT INTO exercises (name, muscle_id, equipment_id) SELECT 'Overhead Tricep Extension (Dumbbell)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Triceps' AND e.name = 'Dumbbells';")
    op.execute("INSERT INTO exercises (name, muscle_id, equipment_id) SELECT 'Pec Deck', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Chest' AND e.name = 'Pec Deck';")
    op.execute("INSERT INTO exercises (name, muscle_id, equipment_id) SELECT 'Preacher Curl (EZ Bar)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Biceps' AND e.name = 'EZ Bar';")
    op.execute("INSERT INTO exercises (name, muscle_id, equipment_id) SELECT 'Romanian Deadlift (Barbell)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Legs' AND e.name = 'Barbell';")
    op.execute("INSERT INTO exercises (name, muscle_id, equipment_id) SELECT 'Romanian Deadlift (Dumbbell)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Legs' AND e.name = 'Dumbbells';")
    op.execute("INSERT INTO exercises (name, muscle_id, equipment_id) SELECT 'Row (Dumbbell)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Back' AND e.name = 'Dumbbells';")
    op.execute("INSERT INTO exercises (name, muscle_id, equipment_id) SELECT 'Run (Treadmill)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Cardio' AND e.name = 'Treadmill';")
    op.execute("INSERT INTO exercises (name, muscle_id, equipment_id) SELECT 'Seated Row', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Back' AND e.name = 'Seated Row Machine';")
    op.execute("INSERT INTO exercises (name, muscle_id, equipment_id) SELECT 'Shrug (Barbell)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Shoulders' AND e.name = 'Barbell';")
    op.execute("INSERT INTO exercises (name, muscle_id, equipment_id) SELECT 'Shrug (Dumbbell)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Shoulders' AND e.name = 'Dumbbells';")
    op.execute("INSERT INTO exercises (name, muscle_id, equipment_id) SELECT 'Skull Crusher (EZ Bar)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Triceps' AND e.name = 'EZ Bar';")
    op.execute("INSERT INTO exercises (name, muscle_id, equipment_id) SELECT 'Tricep Pushdown (Rope)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Triceps' AND e.name = 'Cable Machine';")
    op.execute("INSERT INTO exercises (name, muscle_id, equipment_id) SELECT 'Tricep Pushdown (Straight Bar)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Triceps' AND e.name = 'Cable Machine';")
    op.execute("INSERT INTO exercises (name, muscle_id, equipment_id) SELECT 'Walk (Treadmill)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Cardio' AND e.name = 'Treadmill';")

def downgrade():
    op.execute("DELETE FROM equipment WHERE name = 'Barbell'")
    op.execute("DELETE FROM equipment WHERE name = 'Bench Press Machine'")
    op.execute("DELETE FROM equipment WHERE name = 'Cable Machine'")
    op.execute("DELETE FROM equipment WHERE name = 'Crunch Machine'")
    op.execute("DELETE FROM equipment WHERE name = 'Dumbbells'")
    op.execute("DELETE FROM equipment WHERE name = 'Elliptical'")
    op.execute("DELETE FROM equipment WHERE name = 'EZ Bar'")
    op.execute("DELETE FROM equipment WHERE name = 'Kettlebell'")
    op.execute("DELETE FROM equipment WHERE name = 'Lat Pulldown Machine'")
    op.execute("DELETE FROM equipment WHERE name = 'Leg Curl Machine'")
    op.execute("DELETE FROM equipment WHERE name = 'Leg Extension Machine'")
    op.execute("DELETE FROM equipment WHERE name = 'Leg Press Machine'")
    op.execute("DELETE FROM equipment WHERE name = 'Overhead Press Machine'")
    op.execute("DELETE FROM equipment WHERE name = 'Pec Deck'")
    op.execute("DELETE FROM equipment WHERE name = 'Seated Row Machine'")
    op.execute("DELETE FROM equipment WHERE name = 'Smith Machine'")
    op.execute("DELETE FROM equipment WHERE name = 'Stationary Bicycle'")
    op.execute("DELETE FROM equipment WHERE name = 'Treadmill'")
    op.execute("DELETE FROM muscles WHERE name = 'Abdomen'")
    op.execute("DELETE FROM muscles WHERE name = 'Back'")
    op.execute("DELETE FROM muscles WHERE name = 'Biceps'")
    op.execute("DELETE FROM muscles WHERE name = 'Cardio'")
    op.execute("DELETE FROM muscles WHERE name = 'Chest'")
    op.execute("DELETE FROM muscles WHERE name = 'Legs'")
    op.execute("DELETE FROM muscles WHERE name = 'Shoulders'")
    op.execute("DELETE FROM muscles WHERE name = 'Triceps'")
    op.execute("DELETE FROM exercises WHERE name = 'Back Squat (Barbell)'")
    op.execute("DELETE FROM exercises WHERE name = 'Back Squat (Smith Machine)'")
    op.execute("DELETE FROM exercises WHERE name = 'Bench Press (Decline, Barbell)'")
    op.execute("DELETE FROM exercises WHERE name = 'Bench Press (Decline, Dumbbell)'")
    op.execute("DELETE FROM exercises WHERE name = 'Bench Press (Decline, Smith Machine)'")
    op.execute("DELETE FROM exercises WHERE name = 'Bench Press (Flat, Barbell)'")
    op.execute("DELETE FROM exercises WHERE name = 'Bench Press (Flat, Bench Press Machine)'")
    op.execute("DELETE FROM exercises WHERE name = 'Bench Press (Flat, Dumbbell)'")
    op.execute("DELETE FROM exercises WHERE name = 'Bench Press (Flat, Smith Machine)'")
    op.execute("DELETE FROM exercises WHERE name = 'Bench Press (Incline, Barbell)'")
    op.execute("DELETE FROM exercises WHERE name = 'Bench Press (Incline, Dumbbell)'")
    op.execute("DELETE FROM exercises WHERE name = 'Bench Press (Incline, Smith Machine)'")
    op.execute("DELETE FROM exercises WHERE name = 'Bicep Curl (Cable)'")
    op.execute("DELETE FROM exercises WHERE name = 'Bicep Curl (EZ Bar)'")
    op.execute("DELETE FROM exercises WHERE name = 'Bicep Curl (Incline)'")
    op.execute("DELETE FROM exercises WHERE name = 'Crunch (Cable)'")
    op.execute("DELETE FROM exercises WHERE name = 'Crunch (Machine)'")
    op.execute("DELETE FROM exercises WHERE name = 'Face Pull'")
    op.execute("DELETE FROM exercises WHERE name = 'Goblet Squat'")
    op.execute("DELETE FROM exercises WHERE name = 'Lat Pulldown (Standard)'")
    op.execute("DELETE FROM exercises WHERE name = 'Lat Pulldown (Straight Arm)'")
    op.execute("DELETE FROM exercises WHERE name = 'Lat Pulldown (Underhand)'")
    op.execute("DELETE FROM exercises WHERE name = 'Lat Pulldown (V-Bar)'")
    op.execute("DELETE FROM exercises WHERE name = 'Lateral Raise (Cable)'")
    op.execute("DELETE FROM exercises WHERE name = 'Lateral Raise (Dumbbell)'")
    op.execute("DELETE FROM exercises WHERE name = 'Leg Extension'")
    op.execute("DELETE FROM exercises WHERE name = 'Leg Press'")
    op.execute("DELETE FROM exercises WHERE name = 'Overhead Press (Barbell)'")
    op.execute("DELETE FROM exercises WHERE name = 'Overhead Press (Dumbbell)'")
    op.execute("DELETE FROM exercises WHERE name = 'Overhead Press (Overhead Press Machine)'")
    op.execute("DELETE FROM exercises WHERE name = 'Overhead Press (Smith Machine)'")
    op.execute("DELETE FROM exercises WHERE name = 'Overhead Tricep Extension (Cable)'")
    op.execute("DELETE FROM exercises WHERE name = 'Overhead Tricep Extension (Dumbbell)'")
    op.execute("DELETE FROM exercises WHERE name = 'Pec Deck'")
    op.execute("DELETE FROM exercises WHERE name = 'Preacher Curl (EZ Bar)'")
    op.execute("DELETE FROM exercises WHERE name = 'Romanian Deadlift (Barbell)'")
    op.execute("DELETE FROM exercises WHERE name = 'Romanian Deadlift (Dumbbell)'")
    op.execute("DELETE FROM exercises WHERE name = 'Row (Dumbbell)'")
    op.execute("DELETE FROM exercises WHERE name = 'Run (Treadmill)'")
    op.execute("DELETE FROM exercises WHERE name = 'Seated Row'")
    op.execute("DELETE FROM exercises WHERE name = 'Shrug (Barbell)'")
    op.execute("DELETE FROM exercises WHERE name = 'Shrug (Dumbbell)'")
    op.execute("DELETE FROM exercises WHERE name = 'Skull Crusher (EZ Bar)'")
    op.execute("DELETE FROM exercises WHERE name = 'Tricep Pushdown (Rope)'")
    op.execute("DELETE FROM exercises WHERE name = 'Tricep Pushdown (Straight Bar)'")
    op.execute("DELETE FROM exercises WHERE name = 'Walk (Treadmill)', 'Cardio'")
