"""change weight from integer to float

Revision ID: 723726d05e30
Revises: 4ff0600e5ebd
Create Date: 2025-04-24 09:16:54.268138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '723726d05e30'
down_revision = '4ff0600e5ebd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sets', schema=None) as batch_op:
        batch_op.alter_column('weight',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sets', schema=None) as batch_op:
        batch_op.alter_column('weight',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
