"""seed_data

Revision ID: e8c803d00f78
Revises: 4c77b81b7733
Create Date: 2025-02-13 23:30:19.688038

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'e8c803d00f78'
down_revision = '4c77b81b7733'
branch_labels = None
depends_on = None

def upgrade():
    op.execute("INSERT INTO equipment (id, name, date_added) VALUES (gen_random_uuid(), 'Barbell', TIMEZONE('utc', NOW()));")
    op.execute("INSERT INTO equipment (id, name, date_added) VALUES (gen_random_uuid(), 'Bench Press Machine', TIMEZONE('utc', NOW()));")
    op.execute("INSERT INTO equipment (id, name, date_added) VALUES (gen_random_uuid(), 'Cable Machine', TIMEZONE('utc', NOW()));")
    op.execute("INSERT INTO equipment (id, name, date_added) VALUES (gen_random_uuid(), 'Crunch Machine', TIMEZONE('utc', NOW()));")
    op.execute("INSERT INTO equipment (id, name, date_added) VALUES (gen_random_uuid(), 'Dumbbells', TIMEZONE('utc', NOW()));")
    op.execute("INSERT INTO equipment (id, name, date_added) VALUES (gen_random_uuid(), 'Elliptical', TIMEZONE('utc', NOW()));")
    op.execute("INSERT INTO equipment (id, name, date_added) VALUES (gen_random_uuid(), 'EZ Bar', TIMEZONE('utc', NOW()));")
    op.execute("INSERT INTO equipment (id, name, date_added) VALUES (gen_random_uuid(), 'Kettlebell', TIMEZONE('utc', NOW()));")
    op.execute("INSERT INTO equipment (id, name, date_added) VALUES (gen_random_uuid(), 'Lat Pulldown Machine', TIMEZONE('utc', NOW()));")
    op.execute("INSERT INTO equipment (id, name, date_added) VALUES (gen_random_uuid(), 'Leg Curl Machine', TIMEZONE('utc', NOW()));")
    op.execute("INSERT INTO equipment (id, name, date_added) VALUES (gen_random_uuid(), 'Leg Extension Machine', TIMEZONE('utc', NOW()));")
    op.execute("INSERT INTO equipment (id, name, date_added) VALUES (gen_random_uuid(), 'Leg Press Machine', TIMEZONE('utc', NOW()));")
    op.execute("INSERT INTO equipment (id, name, date_added) VALUES (gen_random_uuid(), 'Overhead Press Machine', TIMEZONE('utc', NOW()));")
    op.execute("INSERT INTO equipment (id, name, date_added) VALUES (gen_random_uuid(), 'Pec Deck', TIMEZONE('utc', NOW()));")
    op.execute("INSERT INTO equipment (id, name, date_added) VALUES (gen_random_uuid(), 'Seated Row Machine', TIMEZONE('utc', NOW()));")
    op.execute("INSERT INTO equipment (id, name, date_added) VALUES (gen_random_uuid(), 'Smith Machine', TIMEZONE('utc', NOW()));")
    op.execute("INSERT INTO equipment (id, name, date_added) VALUES (gen_random_uuid(), 'Stationary Bicycle', TIMEZONE('utc', NOW()));")
    op.execute("INSERT INTO equipment (id, name, date_added) VALUES (gen_random_uuid(), 'Treadmill', TIMEZONE('utc', NOW()));")
    op.execute("INSERT INTO muscles (id, name, date_added) VALUES (gen_random_uuid(), 'Abdomen', TIMEZONE('utc', NOW()));")
    op.execute("INSERT INTO muscles (id, name, date_added) VALUES (gen_random_uuid(), 'Back', TIMEZONE('utc', NOW()));")
    op.execute("INSERT INTO muscles (id, name, date_added) VALUES (gen_random_uuid(), 'Biceps', TIMEZONE('utc', NOW()));")
    op.execute("INSERT INTO muscles (id, name, date_added) VALUES (gen_random_uuid(), 'Cardio', TIMEZONE('utc', NOW()));")
    op.execute("INSERT INTO muscles (id, name, date_added) VALUES (gen_random_uuid(), 'Chest', TIMEZONE('utc', NOW()));")
    op.execute("INSERT INTO muscles (id, name, date_added) VALUES (gen_random_uuid(), 'Legs', TIMEZONE('utc', NOW()));")
    op.execute("INSERT INTO muscles (id, name, date_added) VALUES (gen_random_uuid(), 'Shoulders', TIMEZONE('utc', NOW()));")
    op.execute("INSERT INTO muscles (id, name, date_added) VALUES (gen_random_uuid(), 'Triceps', TIMEZONE('utc', NOW()));")
    op.execute("INSERT INTO exercises (id, date_added, name, muscle_id, equipment_id) SELECT gen_random_uuid(), TIMEZONE('utc', NOW()), 'Back Squat (Barbell)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Legs' AND e.name = 'Barbell';")
    op.execute("INSERT INTO exercises (id, date_added, name, muscle_id, equipment_id) SELECT gen_random_uuid(), TIMEZONE('utc', NOW()), 'Back Squat (Smith Machine)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Legs' AND e.name = 'Smith Machine';")
    op.execute("INSERT INTO exercises (id, date_added, name, muscle_id, equipment_id) SELECT gen_random_uuid(), TIMEZONE('utc', NOW()), 'Bench Press (Decline, Barbell)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Chest' AND e.name = 'Barbell';")
    op.execute("INSERT INTO exercises (id, date_added, name, muscle_id, equipment_id) SELECT gen_random_uuid(), TIMEZONE('utc', NOW()), 'Bench Press (Decline, Dumbbell)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Chest' AND e.name = 'Dumbbells';")
    op.execute("INSERT INTO exercises (id, date_added, name, muscle_id, equipment_id) SELECT gen_random_uuid(), TIMEZONE('utc', NOW()), 'Bench Press (Decline, Smith Machine)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Chest' AND e.name = 'Smith Machine';")
    op.execute("INSERT INTO exercises (id, date_added, name, muscle_id, equipment_id) SELECT gen_random_uuid(), TIMEZONE('utc', NOW()), 'Bench Press (Flat, Barbell)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Chest' AND e.name = 'Barbell';")
    op.execute("INSERT INTO exercises (id, date_added, name, muscle_id, equipment_id) SELECT gen_random_uuid(), TIMEZONE('utc', NOW()), 'Bench Press (Flat, Bench Press Machine)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Chest' AND e.name = 'Bench Press Machine';")
    op.execute("INSERT INTO exercises (id, date_added, name, muscle_id, equipment_id) SELECT gen_random_uuid(), TIMEZONE('utc', NOW()), 'Bench Press (Flat, Dumbbell)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Chest' AND e.name = 'Dumbbells';")
    op.execute("INSERT INTO exercises (id, date_added, name, muscle_id, equipment_id) SELECT gen_random_uuid(), TIMEZONE('utc', NOW()), 'Bench Press (Flat, Smith Machine)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Chest' AND e.name = 'Smith Machine';")
    op.execute("INSERT INTO exercises (id, date_added, name, muscle_id, equipment_id) SELECT gen_random_uuid(), TIMEZONE('utc', NOW()), 'Bench Press (Incline, Barbell)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Chest' AND e.name = 'Barbell';")
    op.execute("INSERT INTO exercises (id, date_added, name, muscle_id, equipment_id) SELECT gen_random_uuid(), TIMEZONE('utc', NOW()), 'Bench Press (Incline, Dumbbell)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Chest' AND e.name = 'Dumbbells';")
    op.execute("INSERT INTO exercises (id, date_added, name, muscle_id, equipment_id) SELECT gen_random_uuid(), TIMEZONE('utc', NOW()), 'Bench Press (Incline, Smith Machine)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Chest' AND e.name = 'Smith Machine';")
    op.execute("INSERT INTO exercises (id, date_added, name, muscle_id, equipment_id) SELECT gen_random_uuid(), TIMEZONE('utc', NOW()), 'Bicep Curl (Cable)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Biceps' AND e.name = 'Cable Machine';")
    op.execute("INSERT INTO exercises (id, date_added, name, muscle_id, equipment_id) SELECT gen_random_uuid(), TIMEZONE('utc', NOW()), 'Bicep Curl (EZ Bar)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Biceps' AND e.name = 'EZ Bar';")
    op.execute("INSERT INTO exercises (id, date_added, name, muscle_id, equipment_id) SELECT gen_random_uuid(), TIMEZONE('utc', NOW()), 'Bicep Curl (Incline)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Biceps' AND e.name = 'Dumbbells';")
    op.execute("INSERT INTO exercises (id, date_added, name, muscle_id, equipment_id) SELECT gen_random_uuid(), TIMEZONE('utc', NOW()), 'Crunch (Cable)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Abdomen' AND e.name = 'Cable Machine';")
    op.execute("INSERT INTO exercises (id, date_added, name, muscle_id, equipment_id) SELECT gen_random_uuid(), TIMEZONE('utc', NOW()), 'Crunch (Machine)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Abdomen' AND e.name = 'Crunch Machine';")
    op.execute("INSERT INTO exercises (id, date_added, name, muscle_id, equipment_id) SELECT gen_random_uuid(), TIMEZONE('utc', NOW()), 'Face Pull', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Shoulders' AND e.name = 'Cable Machine';")
    op.execute("INSERT INTO exercises (id, date_added, name, muscle_id, equipment_id) SELECT gen_random_uuid(), TIMEZONE('utc', NOW()), 'Goblet Squat', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Legs' AND e.name = 'Dumbbells';")
    op.execute("INSERT INTO exercises (id, date_added, name, muscle_id, equipment_id) SELECT gen_random_uuid(), TIMEZONE('utc', NOW()), 'Lat Pulldown (Standard)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Back' AND e.name = 'Lat Pulldown Machine';")
    op.execute("INSERT INTO exercises (id, date_added, name, muscle_id, equipment_id) SELECT gen_random_uuid(), TIMEZONE('utc', NOW()), 'Lat Pulldown (Straight Arm)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Back' AND e.name = 'Lat Pulldown Machine';")
    op.execute("INSERT INTO exercises (id, date_added, name, muscle_id, equipment_id) SELECT gen_random_uuid(), TIMEZONE('utc', NOW()), 'Lat Pulldown (Underhand)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Back' AND e.name = 'Lat Pulldown Machine';")
    op.execute("INSERT INTO exercises (id, date_added, name, muscle_id, equipment_id) SELECT gen_random_uuid(), TIMEZONE('utc', NOW()), 'Lat Pulldown (V-Bar)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Back' AND e.name = 'Lat Pulldown Machine';")
    op.execute("INSERT INTO exercises (id, date_added, name, muscle_id, equipment_id) SELECT gen_random_uuid(), TIMEZONE('utc', NOW()), 'Lateral Raise (Cable)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Shoulders' AND e.name = 'Cable Machine';")
    op.execute("INSERT INTO exercises (id, date_added, name, muscle_id, equipment_id) SELECT gen_random_uuid(), TIMEZONE('utc', NOW()), 'Lateral Raise (Dumbbell)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Shoulders' AND e.name = 'Dumbbells';")
    op.execute("INSERT INTO exercises (id, date_added, name, muscle_id, equipment_id) SELECT gen_random_uuid(), TIMEZONE('utc', NOW()), 'Leg Extension', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Legs' AND e.name = 'Leg Extension Machine';")
    op.execute("INSERT INTO exercises (id, date_added, name, muscle_id, equipment_id) SELECT gen_random_uuid(), TIMEZONE('utc', NOW()), 'Leg Press', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Legs' AND e.name = 'Leg Press Machine';")
    op.execute("INSERT INTO exercises (id, date_added, name, muscle_id, equipment_id) SELECT gen_random_uuid(), TIMEZONE('utc', NOW()), 'Overhead Press (Barbell)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Shoulders' AND e.name = 'Barbell';")
    op.execute("INSERT INTO exercises (id, date_added, name, muscle_id, equipment_id) SELECT gen_random_uuid(), TIMEZONE('utc', NOW()), 'Overhead Press (Dumbbell)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Shoulders' AND e.name = 'Dumbbells';")
    op.execute("INSERT INTO exercises (id, date_added, name, muscle_id, equipment_id) SELECT gen_random_uuid(), TIMEZONE('utc', NOW()), 'Overhead Press (Overhead Press Machine)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Shoulders' AND e.name = 'Overhead Press Machine';")
    op.execute("INSERT INTO exercises (id, date_added, name, muscle_id, equipment_id) SELECT gen_random_uuid(), TIMEZONE('utc', NOW()), 'Overhead Press (Smith Machine)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Shoulders' AND e.name = 'Smith Machine';")
    op.execute("INSERT INTO exercises (id, date_added, name, muscle_id, equipment_id) SELECT gen_random_uuid(), TIMEZONE('utc', NOW()), 'Overhead Tricep Extension (Cable)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Triceps' AND e.name = 'Cable Machine';")
    op.execute("INSERT INTO exercises (id, date_added, name, muscle_id, equipment_id) SELECT gen_random_uuid(), TIMEZONE('utc', NOW()), 'Overhead Tricep Extension (Dumbbell)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Triceps' AND e.name = 'Dumbbells';")
    op.execute("INSERT INTO exercises (id, date_added, name, muscle_id, equipment_id) SELECT gen_random_uuid(), TIMEZONE('utc', NOW()), 'Pec Deck', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Chest' AND e.name = 'Pec Deck';")
    op.execute("INSERT INTO exercises (id, date_added, name, muscle_id, equipment_id) SELECT gen_random_uuid(), TIMEZONE('utc', NOW()), 'Preacher Curl (EZ Bar)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Biceps' AND e.name = 'EZ Bar';")
    op.execute("INSERT INTO exercises (id, date_added, name, muscle_id, equipment_id) SELECT gen_random_uuid(), TIMEZONE('utc', NOW()), 'Romanian Deadlift (Barbell)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Legs' AND e.name = 'Barbell';")
    op.execute("INSERT INTO exercises (id, date_added, name, muscle_id, equipment_id) SELECT gen_random_uuid(), TIMEZONE('utc', NOW()), 'Romanian Deadlift (Dumbbell)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Legs' AND e.name = 'Dumbbells';")
    op.execute("INSERT INTO exercises (id, date_added, name, muscle_id, equipment_id) SELECT gen_random_uuid(), TIMEZONE('utc', NOW()), 'Row (Dumbbell)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Back' AND e.name = 'Dumbbells';")
    op.execute("INSERT INTO exercises (id, date_added, name, muscle_id, equipment_id) SELECT gen_random_uuid(), TIMEZONE('utc', NOW()), 'Run (Treadmill)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Cardio' AND e.name = 'Treadmill';")
    op.execute("INSERT INTO exercises (id, date_added, name, muscle_id, equipment_id) SELECT gen_random_uuid(), TIMEZONE('utc', NOW()), 'Seated Row', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Back' AND e.name = 'Seated Row Machine';")
    op.execute("INSERT INTO exercises (id, date_added, name, muscle_id, equipment_id) SELECT gen_random_uuid(), TIMEZONE('utc', NOW()), 'Shrug (Barbell)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Shoulders' AND e.name = 'Barbell';")
    op.execute("INSERT INTO exercises (id, date_added, name, muscle_id, equipment_id) SELECT gen_random_uuid(), TIMEZONE('utc', NOW()), 'Shrug (Dumbbell)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Shoulders' AND e.name = 'Dumbbells';")
    op.execute("INSERT INTO exercises (id, date_added, name, muscle_id, equipment_id) SELECT gen_random_uuid(), TIMEZONE('utc', NOW()), 'Skull Crusher (EZ Bar)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Triceps' AND e.name = 'EZ Bar';")
    op.execute("INSERT INTO exercises (id, date_added, name, muscle_id, equipment_id) SELECT gen_random_uuid(), TIMEZONE('utc', NOW()), 'Tricep Pushdown (Rope)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Triceps' AND e.name = 'Cable Machine';")
    op.execute("INSERT INTO exercises (id, date_added, name, muscle_id, equipment_id) SELECT gen_random_uuid(), TIMEZONE('utc', NOW()), 'Tricep Pushdown (Straight Bar)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Triceps' AND e.name = 'Cable Machine';")
    op.execute("INSERT INTO exercises (id, date_added, name, muscle_id, equipment_id) SELECT gen_random_uuid(), TIMEZONE('utc', NOW()), 'Walk (Treadmill)', m.id, e.id FROM muscles m, equipment e WHERE m.name = 'Cardio' AND e.name = 'Treadmill';")

def downgrade():
    op.execute("DELETE FROM equipment WHERE name = 'Barbell'")
    op.execute("DELETE FROM equipment WHERE name = 'Bench Press Machine'")
    op.execute("DELETE FROM equipment WHERE name = 'Cable Machine'")
    op.execute("DELETE FROM equipment WHERE name = 'Crunch Machine'")
    op.execute("DELETE FROM equipment WHERE name = 'Dumbbells'")
    op.execute("DELETE FROM equipment WHERE name = 'Elliptical'")
    op.execute("DELETE FROM equipment WHERE name = 'EZ Bar'")
    op.execute("DELETE FROM equipment WHERE name = 'Kettlebell'")
    op.execute("DELETE FROM equipment WHERE name = 'Lat Pulldown Machine'")
    op.execute("DELETE FROM equipment WHERE name = 'Leg Curl Machine'")
    op.execute("DELETE FROM equipment WHERE name = 'Leg Extension Machine'")
    op.execute("DELETE FROM equipment WHERE name = 'Leg Press Machine'")
    op.execute("DELETE FROM equipment WHERE name = 'Overhead Press Machine'")
    op.execute("DELETE FROM equipment WHERE name = 'Pec Deck'")
    op.execute("DELETE FROM equipment WHERE name = 'Seated Row Machine'")
    op.execute("DELETE FROM equipment WHERE name = 'Smith Machine'")
    op.execute("DELETE FROM equipment WHERE name = 'Stationary Bicycle'")
    op.execute("DELETE FROM equipment WHERE name = 'Treadmill'")
    op.execute("DELETE FROM muscles WHERE name = 'Abdomen'")
    op.execute("DELETE FROM muscles WHERE name = 'Back'")
    op.execute("DELETE FROM muscles WHERE name = 'Biceps'")
    op.execute("DELETE FROM muscles WHERE name = 'Cardio'")
    op.execute("DELETE FROM muscles WHERE name = 'Chest'")
    op.execute("DELETE FROM muscles WHERE name = 'Legs'")
    op.execute("DELETE FROM muscles WHERE name = 'Shoulders'")
    op.execute("DELETE FROM muscles WHERE name = 'Triceps'")
    op.execute("DELETE FROM exercises WHERE name = 'Back Squat (Barbell)'")
    op.execute("DELETE FROM exercises WHERE name = 'Back Squat (Smith Machine)'")
    op.execute("DELETE FROM exercises WHERE name = 'Bench Press (Decline, Barbell)'")
    op.execute("DELETE FROM exercises WHERE name = 'Bench Press (Decline, Dumbbell)'")
    op.execute("DELETE FROM exercises WHERE name = 'Bench Press (Decline, Smith Machine)'")
    op.execute("DELETE FROM exercises WHERE name = 'Bench Press (Flat, Barbell)'")
    op.execute("DELETE FROM exercises WHERE name = 'Bench Press (Flat, Bench Press Machine)'")
    op.execute("DELETE FROM exercises WHERE name = 'Bench Press (Flat, Dumbbell)'")
    op.execute("DELETE FROM exercises WHERE name = 'Bench Press (Flat, Smith Machine)'")
    op.execute("DELETE FROM exercises WHERE name = 'Bench Press (Incline, Barbell)'")
    op.execute("DELETE FROM exercises WHERE name = 'Bench Press (Incline, Dumbbell)'")
    op.execute("DELETE FROM exercises WHERE name = 'Bench Press (Incline, Smith Machine)'")
    op.execute("DELETE FROM exercises WHERE name = 'Bicep Curl (Cable)'")
    op.execute("DELETE FROM exercises WHERE name = 'Bicep Curl (EZ Bar)'")
    op.execute("DELETE FROM exercises WHERE name = 'Bicep Curl (Incline)'")
    op.execute("DELETE FROM exercises WHERE name = 'Crunch (Cable)'")
    op.execute("DELETE FROM exercises WHERE name = 'Crunch (Machine)'")
    op.execute("DELETE FROM exercises WHERE name = 'Face Pull'")
    op.execute("DELETE FROM exercises WHERE name = 'Goblet Squat'")
    op.execute("DELETE FROM exercises WHERE name = 'Lat Pulldown (Standard)'")
    op.execute("DELETE FROM exercises WHERE name = 'Lat Pulldown (Straight Arm)'")
    op.execute("DELETE FROM exercises WHERE name = 'Lat Pulldown (Underhand)'")
    op.execute("DELETE FROM exercises WHERE name = 'Lat Pulldown (V-Bar)'")
    op.execute("DELETE FROM exercises WHERE name = 'Lateral Raise (Cable)'")
    op.execute("DELETE FROM exercises WHERE name = 'Lateral Raise (Dumbbell)'")
    op.execute("DELETE FROM exercises WHERE name = 'Leg Extension'")
    op.execute("DELETE FROM exercises WHERE name = 'Leg Press'")
    op.execute("DELETE FROM exercises WHERE name = 'Overhead Press (Barbell)'")
    op.execute("DELETE FROM exercises WHERE name = 'Overhead Press (Dumbbell)'")
    op.execute("DELETE FROM exercises WHERE name = 'Overhead Press (Overhead Press Machine)'")
    op.execute("DELETE FROM exercises WHERE name = 'Overhead Press (Smith Machine)'")
    op.execute("DELETE FROM exercises WHERE name = 'Overhead Tricep Extension (Cable)'")
    op.execute("DELETE FROM exercises WHERE name = 'Overhead Tricep Extension (Dumbbell)'")
    op.execute("DELETE FROM exercises WHERE name = 'Pec Deck'")
    op.execute("DELETE FROM exercises WHERE name = 'Preacher Curl (EZ Bar)'")
    op.execute("DELETE FROM exercises WHERE name = 'Romanian Deadlift (Barbell)'")
    op.execute("DELETE FROM exercises WHERE name = 'Romanian Deadlift (Dumbbell)'")
    op.execute("DELETE FROM exercises WHERE name = 'Row (Dumbbell)'")
    op.execute("DELETE FROM exercises WHERE name = 'Run (Treadmill)'")
    op.execute("DELETE FROM exercises WHERE name = 'Seated Row'")
    op.execute("DELETE FROM exercises WHERE name = 'Shrug (Barbell)'")
    op.execute("DELETE FROM exercises WHERE name = 'Shrug (Dumbbell)'")
    op.execute("DELETE FROM exercises WHERE name = 'Skull Crusher (EZ Bar)'")
    op.execute("DELETE FROM exercises WHERE name = 'Tricep Pushdown (Rope)'")
    op.execute("DELETE FROM exercises WHERE name = 'Tricep Pushdown (Straight Bar)'")
    op.execute("DELETE FROM exercises WHERE name = 'Walk (Treadmill)', 'Cardio'")
