"""add duration and completed fields

Revision ID: 36a664723dc4
Revises: 09725f7a6a56
Create Date: 2025-12-22 03:55:53.796337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36a664723dc4'
down_revision: Union[str, Sequence[str], None] = '09725f7a6a56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sets', sa.Column('completed', sa.Boolean(), nullable=True))
    op.alter_column('sets', 'weight',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.add_column('workouts', sa.Column('duration', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workouts', 'duration')
    op.alter_column('sets', 'weight',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('sets', 'completed')
    # ### end Alembic commands ###
