"""add_muscles_to_workout_exercises

Revision ID: a42bfa096a88
Revises: f0ecf7decd98
Create Date: 2025-12-22 04:45:45.984044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a42bfa096a88'
down_revision: Union[str, Sequence[str], None] = 'f0ecf7decd98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout_exercises', sa.Column('muscles', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workout_exercises', 'muscles')
    # ### end Alembic commands ###
